#pragma once

#define RKIT_PLATFORM_ARCH_FAMILY_X86 1
#define RKIT_PLATFORM_ARCH_X64 1

#define RKIT_PLATFORM_COMPILER_FAMILY_MSVC	1
#define RKIT_PLATFORM_COMPILER_MSVC	1

#ifdef _MSC_VER
#	define RKIT_PLATFORM_COMPILER_FAMILY RKIT_PLATFORM_COMPILER_FAMILY_MSVC
#	define RKIT_PLATFORM_COMPILER	RKIT_PLATFORM_COMPILER_MSVC
#	ifdef _M_X64
#		define RKIT_PLATFORM_ARCH_FAMILY RKIT_PLATFORM_ARCH_FAMILY_X86
#		define RKIT_PLATFORM_ARCH RKIT_PLATFORM_ARCH_X64
#		define RKIT_PLATFORM_ARCH_HAVE_SSE 1
#		define RKIT_PLATFORM_ARCH_HAVE_SSE2 1
//#		define RKIT_PLATFORM_ARCH_HAVE_SSE41 1
#	else
#		error "Need to implement this"
#	endif
#else
#	error "Need to implement this"
#endif

#ifndef RKIT_PLATFORM_ARCH_HAVE_SSE
#	define RKIT_PLATFORM_ARCH_HAVE_SSE 0
#endif

#ifndef RKIT_PLATFORM_ARCH_HAVE_SSE2
#	define RKIT_PLATFORM_ARCH_HAVE_SSE2 0
#endif

#ifndef RKIT_PLATFORM_ARCH_HAVE_SSE41
#	define RKIT_PLATFORM_ARCH_HAVE_SSE41 0
#endif
